name: Peter Indiola - Front-end, Ruby on Rails and iOS Developer based in the Philippines.
description: Hi, I'm Peter Indiola you found my site!
meta_description: "This site where I post everything I think worth sharing"
aboutPage: true
markdown: redcarpet
# highlighter: pygments

# paginate: 20
baseurl: /
domain_name: 'http://pindiola.me'
google_analytics: 'UA-74100318-1'
disqus: true
disqus_shortname: 'pindiolame.disqus.com'

# Details for the RSS feed generator
url:            'http://pindiola.me'
author:         'Peter Indiola'
authorTwitter:  'pindiola'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
